// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjddzwjlvaxgiwhwkwcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZGR6d2psdmF4Z2l3aHdrd2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjEzMDgsImV4cCI6MjA1ODc5NzMwOH0.Jhb2yRQwd3_PQsJQ8BQ9DxK1oNtH31kXvZXCD2r9q5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);